config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "static_pages#home"
  get "sessions/new"
  get "static_pages/home"
  get "static_pages/help"
  get "static_pages/about"
  get "static_pages/contact"
  get "/signup", to: "users#new"
  post "/signup", to: "users#create"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: :edit
  resources :password_resets, only: %i(new create edit update)
  resources :microposts, only: %i(create destroy)
  resources :relationships, only: %i(create destroy)
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t "footer.text_1" %> <a href="https://www.railstutorial.org/"> <%= t "footer.text_2" %></a>
    <%= t "footer.text_3" %> <a href="http://www.michaelhartl.com/"><%= t "footer.text_4" %></a>
  </small>
  <nav>
    <ul>
      <li><%= link_to t("static_pages.about.title"),   static_pages_about_path %></li>
      <li><%= link_to t("static_pages.contact.title"), static_pages_contact_path %></li>
      <li><%= link_to t("footer.news"), 'http://news.railstutorial.org/' %></li>
    </ul>
  </nav>
  <br/>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <div class="container">
      <%= link_to t("header.sample_app"), "#", id: "logo", class: "nav-brand" %>

      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to t("header.home"), static_pages_home_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to t("header.help"), static_pages_help_path, class: "nav-link" %>
        </li>
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to t("header.users"), users_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= link_to t("static_pages.home.account"),
              "#",
              class: "nav-link dropdown-toggle",
              id: "navbarDropdownMenuLink",
              data: {toggle: "dropdown"},
              aria: {haspopup: "true", expanded: "false"} %>
            <div class="dropdown-menu dropdown-menu-right" 
                  aria-labelledby="navbarDropdownMenuLink">
              <%= link_to t("static_pages.home.profile"), current_user, class: "dropdown-item" %>
              <%= link_to t("static_pages.home.settings"), edit_user_path(current_user), class: "dropdown-item" %>
              <div class="dropdown-divider"></div>
              <%= link_to t("static_pages.home.logout"), logout_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li><%= link_to t("log_in"), login_path, class: "nav-link" %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield :title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <p class="text-center"><%= t "text_PR" %></p>
      <%= render "layouts/footer" %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>